import 'package:json_annotation/json_annotation.dart';

part 'simulation_outcome.g.dart';

/// Type of outcome for a simulated position
enum OutcomeType {
  /// Property was redeemed, investor received principal + interest
  redeemed,

  /// Property was foreclosed, investor owns the property
  foreclosed,

  /// Partial payment received, reduced returns
  partialPayment,

  /// Investment lost (rare, but possible)
  loss,
}

/// Represents the outcome of a simulated property investment
///
/// Contains details about what happened with the investment,
/// including financial results and educational insights.
@JsonSerializable()
class SimulationOutcome {
  /// Unique identifier for this outcome
  final String id;

  /// ID of the position this outcome belongs to
  final String positionId;

  /// Type of outcome
  @JsonKey(unknownEnumValue: OutcomeType.loss)
  final OutcomeType type;

  /// Final value received from the investment
  final double finalValue;

  /// Profit or loss amount (finalValue - totalCost)
  final double profitLoss;

  /// ROI percentage
  final double roiPercentage;

  /// Number of simulated weeks from purchase to outcome
  final int weeksToOutcome;

  /// Probability that was used to determine this outcome (0.0 to 1.0)
  final double probability;

  /// Whether this outcome was generated by ML or rule-based fallback
  final bool isMlGenerated;

  /// Educational lesson learned from this outcome
  final String lessonLearned;

  /// Detailed explanation of what happened
  final String explanation;

  /// Timestamp when outcome was generated
  final DateTime generatedAt;

  /// Additional metadata (e.g., ML confidence, county stats)
  final Map<String, dynamic>? metadata;

  const SimulationOutcome({
    required this.id,
    required this.positionId,
    required this.type,
    required this.finalValue,
    required this.profitLoss,
    required this.roiPercentage,
    required this.weeksToOutcome,
    required this.probability,
    required this.isMlGenerated,
    required this.lessonLearned,
    required this.explanation,
    required this.generatedAt,
    this.metadata,
  });

  /// Whether this outcome was successful (positive return)
  bool get isSuccess => profitLoss > 0;

  /// Whether this outcome was a loss
  bool get isLoss => profitLoss < 0;

  /// Create a copy with updated fields
  SimulationOutcome copyWith({
    String? id,
    String? positionId,
    OutcomeType? type,
    double? finalValue,
    double? profitLoss,
    double? roiPercentage,
    int? weeksToOutcome,
    double? probability,
    bool? isMlGenerated,
    String? lessonLearned,
    String? explanation,
    DateTime? generatedAt,
    Map<String, dynamic>? metadata,
  }) {
    return SimulationOutcome(
      id: id ?? this.id,
      positionId: positionId ?? this.positionId,
      type: type ?? this.type,
      finalValue: finalValue ?? this.finalValue,
      profitLoss: profitLoss ?? this.profitLoss,
      roiPercentage: roiPercentage ?? this.roiPercentage,
      weeksToOutcome: weeksToOutcome ?? this.weeksToOutcome,
      probability: probability ?? this.probability,
      isMlGenerated: isMlGenerated ?? this.isMlGenerated,
      lessonLearned: lessonLearned ?? this.lessonLearned,
      explanation: explanation ?? this.explanation,
      generatedAt: generatedAt ?? this.generatedAt,
      metadata: metadata ?? this.metadata,
    );
  }

  /// Generate a unique ID for an outcome
  static String _generateId() {
    return 'outcome_${DateTime.now().millisecondsSinceEpoch}_${DateTime.now().microsecondsSinceEpoch % 1000}';
  }

  /// Create a new outcome (typically called by simulation service)
  factory SimulationOutcome.generate({
    required String positionId,
    required OutcomeType type,
    required double purchasePrice,
    required double transactionFees,
    required int weeksToOutcome,
    required double probability,
    required bool isMlGenerated,
    Map<String, dynamic>? metadata,
  }) {
    final totalCost = purchasePrice + transactionFees;
    final (finalValue, lesson, explanation) = _calculateOutcomeDetails(
      type: type,
      purchasePrice: purchasePrice,
      totalCost: totalCost,
      weeksToOutcome: weeksToOutcome,
    );

    final profitLoss = finalValue - totalCost;
    final roiPercentage = (profitLoss / totalCost) * 100;

    return SimulationOutcome(
      id: _generateId(),
      positionId: positionId,
      type: type,
      finalValue: finalValue,
      profitLoss: profitLoss,
      roiPercentage: roiPercentage,
      weeksToOutcome: weeksToOutcome,
      probability: probability,
      isMlGenerated: isMlGenerated,
      lessonLearned: lesson,
      explanation: explanation,
      generatedAt: DateTime.now(),
      metadata: metadata,
    );
  }

  /// Calculate outcome-specific details
  static (double, String, String) _calculateOutcomeDetails({
    required OutcomeType type,
    required double purchasePrice,
    required double totalCost,
    required int weeksToOutcome,
  }) {
    switch (type) {
      case OutcomeType.redeemed:
        // Typical interest rate ~15% annually
        final annualRate = 0.15;
        final years = weeksToOutcome / 52.0;
        final finalValue = totalCost * (1 + annualRate * years);
        return (
          finalValue,
          'Property owners often redeem before foreclosure. Steady returns with lower risk.',
          'The property owner redeemed the tax lien by paying the owed taxes plus interest. You received your principal back plus ${(finalValue - totalCost).toStringAsFixed(2)} in interest.',
        );

      case OutcomeType.foreclosed:
        // Typically 2-3x purchase price in property value
        final propertyValue = purchasePrice * (2.0 + (weeksToOutcome / 52.0) * 0.5);
        return (
          propertyValue,
          'Foreclosure can yield high returns but requires property management expertise.',
          'The property was not redeemed, and you now own it through foreclosure. The property is estimated to be worth \$${propertyValue.toStringAsFixed(2)}, giving you significant equity.',
        );

      case OutcomeType.partialPayment:
        // 50-80% of expected return
        final expectedReturn = totalCost * 1.15;
        final finalValue = totalCost + (expectedReturn - totalCost) * 0.65;
        return (
          finalValue,
          'Partial payments are common. Diversification helps manage this risk.',
          'The property owner made a partial payment. You recovered your investment plus some interest, but less than the full expected return.',
        );

      case OutcomeType.loss:
        // Rare, typically 10-30% loss
        final finalValue = totalCost * 0.85;
        return (
          finalValue,
          'Losses can happen due to title issues or legal complications. Due diligence is critical.',
          'Unfortunately, this investment resulted in a loss due to unforeseen legal complications. This is rare but highlights the importance of thorough research.',
        );
    }
  }

  /// JSON serialization
  factory SimulationOutcome.fromJson(Map<String, dynamic> json) =>
      _$SimulationOutcomeFromJson(json);

  Map<String, dynamic> toJson() => _$SimulationOutcomeToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulationOutcome &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'SimulationOutcome(id: $id, type: $type, roi: ${roiPercentage.toStringAsFixed(2)}%, profitLoss: \$${profitLoss.toStringAsFixed(2)})';
  }
}
